[package]
name = "dynamic_perfect_hashing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxhash = "0.2.1"
ahash = "0.7.4"
fnv = "1.0.7"
queues = "1.0.0"